### ISSUE TITLE
Error during installing NJOY21 on Ubuntu20.04LTS

### ISSUE THREAD

**Issue by ternence6** [njoy/signatures#4]
after `wget https://github.com/njoy/signatures/blob/master/NJOY21/1.1.0-NJOY21.json`
when running `./metaconfigure/fetch_subprojects.py 1.1.0-NJOY21.json`
mistakes occured.
![批注 2020-05-01 180003](https://user-images.githubusercontent.com/59700286/80797953-b2116200-8bd5-11ea-99c3-e4f9701673df.png)

**Comment by jlconlin** [comment]
I can confirm what you are seeing. However, please not that the URL that you are using does not point to the file directly. Rather, you are seeing the page from which it can be downloaded. Please use the URL given in the [instructions](http://www.njoy21.io/Build/index.html):

https://raw.githubusercontent.com/njoy/signatures/master/NJOY21/1.1.0-NJOY21.json

Hopefully this will help.

**Comment by ternence6** [comment]
Are these two signature files different or？

**Comment by jlconlin** [comment]
The URL that I provided (which is also the one in the build instructions) points to the appropriate JSON file. The URL that you provided points to a web page on GitHub—where you see the contents of the JSON file—but is not the JSON file itself. Visit it yourself and see.

**Comment by ternence6** [comment]
> The URL that I provided (which is also the one in the build instructions) points to the appropriate JSON file. The URL that you provided points to a web page on GitHub—where you see the contents of the JSON file—but is not the JSON file itself. Visit it yourself and see.

it works，thank you:)
